[theme]
primaryColor="#4A56A6"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"

[server]
runOnSave = true
enableStaticServing = true

[browser]
gatherUsageStats = false 