# Groq API key
GROQ_API_KEY = "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"

# Uncomment and add your OpenAI API key if needed
# OPENAI_API_KEY = "your-openai-api-key"

# Uncomment and add your Hugging Face API token if needed
# HUGGINGFACEHUB_API_TOKEN = "your-huggingface-token" 